### ISSUE TITLE
Add: Total up times/numbers at beginning of tasks

### ISSUE THREAD

**Issue by blanchardjeremy** [phaistonian/Asana-Plus#1]
Asana used to offer a "hack" that would show you the numbers at the beginning of tasks in brackets (used for time estimates, usually) when you select multiple tasks.

So if I had the following tasks:

[12m] Arena + Council: Open check-in
[5m] Set roles, Celebrate what is working
[10m] Review & update Focus Dashboard
[10m] Finalize agenda (including harvest from Council)
[2m] Review Actions
[5m] Name upcoming Enrollment & Staff meeting facilitator

Then **44** would show up in the right sidebar.

This feature was recently moved to only be a part of "pro" accounts. It's such a useful tool.

Could you add that to your plugin?

**Comment by phaistonian** [comment]
Can you provide a screenshot of how it looked like?

**Comment by blanchardjeremy** [comment]
Yes, here is one example: ![](https://pbs.twimg.com/media/BkVAFoKCAAAZIsH.png)

**Comment by phaistonian** [comment]
I believe it's doable.

If no one else volunteers for this one, I will get on it when I get some free time.

**Comment by blanchardjeremy** [comment]
Okay. Thanks so much. I'm happy to help with any testing if that is useful!

**Comment by blanchardjeremy** [comment]
Also, let me know if there's any support I can provide in advance of the coding. I'm very excited to see this feature exist!

**Comment by phaistonian** [comment]
![image](https://cloud.githubusercontent.com/assets/796530/25080264/a43035da-234b-11e7-8f04-e7767f0a4bae.png)

Should be done - uploading a new version in 5'.

**Comment by blanchardjeremy** [comment]
![screen shot 2017-04-17 at 11 04 02 am](https://cloud.githubusercontent.com/assets/32290/25098670/47da82be-235e-11e7-801d-88523e4f496b.png)

There are two bugs I see:
* When I highlight two items (either in format [5] or [5m] format), all I see as a result is: []
* When I highlight two items that do NOT start with [5], it still shows the same result: []

Let me know how I can support with helping you debug!

PS - Perhaps we should test it a bit more before publishing a release. :)

**Comment by phaistonian** [comment]
Hey @auzigog.

Just uploaded a new version with those fixes.

Should be fine this time.

ps: Finding even a couple minutes (to work on this extension) is really hard these days.

**Comment by blanchardjeremy** [comment]
![screen shot 2017-04-18 at 10 14 31 am](https://cloud.githubusercontent.com/assets/32290/25143605/edfc3edc-241f-11e7-8ada-3eab71d3bae5.png)

Now nothing happens when I highlight anything.

PS - Thanks for making time to work on this extension, buddy! I appreciate your dedication to it. :)

**Comment by phaistonian** [comment]
Oh snap.

Fixed the bug and just pushed an new version.

Should do the trick now :)

(new version could take up to 40m to show up)

**Comment by blanchardjeremy** [comment]
Great. Is the latest one 0.13.0 in Chrome's version history?

**Comment by blanchardjeremy** [comment]
![screen shot 2017-04-19 at 3 50 55 pm](https://cloud.githubusercontent.com/assets/32290/25205543/04688bdc-2518-11e7-88a3-05fce7dd3901.png)

This is version 0.13.0

Looks like it's still not working. Nothing is showing up.

**Comment by phaistonian** [comment]
Okat, I figured this (mess) out.

Apparently Asana uses a different layout / scheme for when browsing a project as opposed to when in "my items" view.

The latest version (0.15) should do the trick.

**Comment by blanchardjeremy** [comment]
Wahoo! In my initial testing, it works great! I'll close the issue for now and re-open it if I encounter any bugs.

Thanks for taking the time to improve this!

**Comment by blanchardjeremy** [comment]
One more bug: If you use shift+click to highlight multiple items, this feature works great. If you use shift+up to highlight multiple items, it doesn't work.

**Comment by phaistonian** [comment]
Should be done - not tested:)

**Comment by blanchardjeremy** [comment]
Working great! Thanks so much!
